"""Added Cascades

Revision ID: 7139c8d8d9a2
Revises: dc715dc03b6b
Create Date: 2025-12-12 19:18:47.681522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7139c8d8d9a2'
down_revision: Union[str, Sequence[str], None] = 'dc715dc03b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_members_project_id_fkey'), 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key(op.f('project_members_project_id_fkey'), 'project_members', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
