"""Realtionships Between Project, Project Members, and Users.

Revision ID: dc715dc03b6b
Revises: edc303f79def
Create Date: 2025-12-12 17:37:25.409718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc715dc03b6b'
down_revision: Union[str, Sequence[str], None] = 'edc303f79def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('tech_stack', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'tech_stack')
    # ### end Alembic commands ###
